version: 2
jobs:
  py3test:
    working_directory: ~/pymatgen-diffusion
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:3.7.3
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            conda config --set always_yes yes --set changeps1 no
            conda update -q conda
            conda info -a
            conda create -q -n test-environment python=3.7 numpy scipy matplotlib sympy pandas networkx pytest
            source activate test-environment
            conda update --quiet numpy scipy matplotlib sympy pandas networkx pytest pip
            pip install --quiet --ignore-installed -r requirements.txt -r requirements-ci.txt
      - run:
          command: |
            # Add executables and path.
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            source activate test-environment
            pip install --quiet -e .
            pytest --cov=pymatgen_diffusion --cov-report html:coverage_reports --durations=30 pymatgen_diffusion
            pycodestyle pymatgen_diffusion
          no_output_timeout: 3600
      - store_artifacts:
          path: coverage_reports/
          destination: tr1
      - store_test_results:
          path: coverage_reports/

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
